$background = 130d0a
$onBackground = f9e0d8
$surface = 130d0a
$surfaceDim = 130d0a
$surfaceBright = 372924
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a110e
$surfaceContainer = 211713
$surfaceContainerHigh = 281d19
$surfaceContainerHighest = 30231d
$onSurface = f9e0d8
$surfaceVariant = 30231d
$onSurfaceVariant = bca79f
$outline = 84716a
$outlineVariant = 54443e
$inverseSurface = fff8f6
$inverseOnSurface = 5d534f
$shadow = 000000
$scrim = 000000
$surfaceTint = f8b89e
$primary = f8b89e
$primaryDim = e9aa91
$onPrimary = 603522
$primaryContainer = 754733
$onPrimaryContainer = ffdccf
$inversePrimary = 84533e
$primaryFixed = febda3
$primaryFixedDim = efb097
$onPrimaryFixed = 4d2514
$onPrimaryFixedVariant = 6f412e
$secondary = e7beae
$secondaryDim = d8b0a1
$onSecondary = 553a2e
$secondaryContainer = 50352a
$onSecondaryContainer = dfb7a7
$secondaryFixed = ffdbcd
$secondaryFixedDim = f5cbbb
$onSecondaryFixed = 54392d
$onSecondaryFixedVariant = 745448
$tertiary = ffe9ba
$tertiaryDim = f7da96
$onTertiary = 69541e
$tertiaryContainer = f7da96
$onTertiaryContainer = 604c16
$tertiaryFixed = f7da96
$tertiaryFixedDim = e9cc89
$onTertiaryFixed = 4b3904
$onTertiaryFixedVariant = 6a551f
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 9f6a54
$secondaryPaletteKeyColor = 916f62
$tertiaryPaletteKeyColor = 8b743a
$neutralPaletteKeyColor = 817571
$neutralVariantPaletteKeyColor = 86736c
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 9f6a54
$secondary_paletteKeyColor = 916f62
$tertiary_paletteKeyColor = 8b743a
$neutral_paletteKeyColor = 817571
$neutral_variant_paletteKeyColor = 86736c
$term0 = 353433
$term1 = ff5801
$term2 = ffbe90
$term3 = ffe0d0
$term4 = b9ab66
$term5 = f1917a
$term6 = ffbb7c
$term7 = eed3c5
$term8 = b49e94
$term9 = ff885a
$term10 = ffd5b9
$term11 = fff1eb
$term12 = dcbc93
$term13 = ffaa93
$term14 = ffd3ae
$term15 = ffffff
$rosewater = ffeee9
$flamingo = ffdacf
$pink = ffd3cb
$mauve = ffaaa4
$red = ff997d
$maroon = f9ab95
$peach = ffbfa4
$yellow = ffeee5
$green = ffd9b9
$teal = ffdb94
$sky = e1df87
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbbbc
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5d52
$kvisitedSelection = cf5d53
$knegative = e85925
$knegativeSelection = e95928
$kneutral = ff8b53
$kneutralSelection = ff8b55
$kpositive = f49104
$kpositiveSelection = f59109
$text = f9e0d8
$subtext1 = bca79f
$subtext0 = 84716a
$overlay2 = 74635c
$overlay1 = 63544e
$overlay0 = 534641
$surface2 = 443934
$surface1 = 342b27
$surface0 = 241c18
$base = 130d0a
$mantle = 130d0a
$crust = 120c09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
