general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = notify-send "Welcome Back!"
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = wlopm --on '*'
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # whether to ignore systemd-inhibit --what=idle inhibitors
}

# bajar brillo en 2.5 minutos de inactividad
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# en 4 minutos de inactividad se bloquea la pantalla
listener {
    timeout = 240
    on-timeout = loginctl lock-session
}

# apagar la pantalla en 5 minutos
listener {
    timeout = 300
    on-timeout = wlopm --off '*'
    on-resume = wlopm --on '*'
}

# suspender en 8 minutos
listener {
    timeout = 480
    # usa "systemctl hibernate" si se tiene swap configurado o "systemctl suspend"
    on-timeout = systemctl suspend
}
