exec-once = /usr/lib/pam_kwallet_init

input {
	kb_layout = latam
}

# Forzar una escala más grande para todas las pantallas
monitor = , preferred, auto, 1.25

cursor:no_hardware_cursors = 0

xwayland {
	force_zero_scaling = true
}
