$background = 0a0f0f
$onBackground = dce8e8
$surface = 0a0f0f
$surfaceDim = 0a0f0f
$surfaceBright = 242e2f
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0e1515
$surfaceContainer = 131b1b
$surfaceContainerHigh = 192122
$surfaceContainerHighest = 1d2828
$onSurface = dce8e8
$surfaceVariant = 1d2828
$onSurfaceVariant = a2adae
$outline = 6d7778
$outlineVariant = 3f4a4a
$inverseSurface = f6fafa
$inverseOnSurface = 515656
$shadow = 000000
$scrim = 000000
$surfaceTint = 9bd0d3
$primary = 9bd0d3
$primaryDim = 8ec2c5
$onPrimary = 0c474b
$primaryContainer = 255a5d
$onPrimaryContainer = b8edf0
$inversePrimary = 33676a
$primaryFixed = b7ecef
$primaryFixedDim = a9dee1
$onPrimaryFixed = 0b474a
$onPrimaryFixedVariant = 2f6367
$secondary = b1cccd
$secondaryDim = a3bebf
$onSecondary = 2c4446
$secondaryContainer = 273f41
$onSecondaryContainer = a9c4c6
$secondaryFixed = cce8e9
$secondaryFixedDim = bedadb
$onSecondaryFixed = 2b4345
$onSecondaryFixedVariant = 476061
$tertiary = cfe8ff
$tertiaryDim = b5dcfc
$onTertiary = 315772
$tertiaryContainer = b5dcfc
$onTertiaryContainer = 274f69
$tertiaryFixed = b5dcfc
$tertiaryFixedDim = a8ceee
$onTertiaryFixed = 103b55
$onTertiaryFixedVariant = 325873
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 4c7f82
$secondaryPaletteKeyColor = 627c7e
$tertiaryPaletteKeyColor = 567b98
$neutralPaletteKeyColor = 737878
$neutralVariantPaletteKeyColor = 6e797a
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 4c7f82
$secondary_paletteKeyColor = 627c7e
$tertiary_paletteKeyColor = 567b98
$neutral_paletteKeyColor = 737878
$neutral_variant_paletteKeyColor = 6e797a
$term0 = 343434
$term1 = 769e00
$term2 = 4be2cc
$term3 = 77fcdb
$term4 = 76b5b9
$term5 = 7aaee9
$term6 = 81d8d1
$term7 = ccdcd5
$term8 = 9aa59f
$term9 = 85b900
$term10 = 2bf7de
$term11 = cbffef
$term12 = a3c8c7
$term13 = a2c0f7
$term14 = 88ece2
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 66cdef
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d1faed
$green = 8bf1e9
$teal = 9eedee
$sky = 93e9f0
$sapphire = 72d6e3
$blue = 5bcbe2
$lavender = 88d8ee
$klink = 0095a6
$klinkSelection = 0095a7
$kvisited = 008cae
$kvisitedSelection = 008cb0
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bdb6
$kpositiveSelection = 00bdb8
$text = dce8e8
$subtext1 = a2adae
$subtext0 = 6d7778
$overlay2 = 5f6869
$overlay1 = 505959
$overlay0 = 434a4b
$surface2 = 353c3d
$surface1 = 282e2e
$surface0 = 191e1f
$base = 0a0f0f
$mantle = 0a0f0f
$crust = 090e0e
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
