[Login]
# Suspender al cerrar la tapa tanto con batería como con cargador
# HandleLidSwitch=suspend
# HandleLidSwitchExternalPower=suspend
# Si hay pantalla externa conectada o está en dock, cambiar a 'ignore' para no suspender
# HandleLidSwitchDocked=suspend
