[config]
# Prefijo opcional para recarga de apps o configuración general

# Plantilla para Hyprland (Lua)
[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/scheme/current.lua"
post_hook = "hyprctl reload"

# plantilla para eww bar
[templates.eww]
input_path = "~/.config/matugen/templates/eww-colors.scss"
output_path = "~/.config/eww/bar/color.scss"
post_hook = "eww -c ~/Dotfiles/config/eww/bar open bar"

# plantilla para rofi
[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/themes/colors.rasi"
