$background = 0d0f0a
$onBackground = e3e7d8
$surface = 0d0f0a
$surfaceDim = 0d0f0a
$surfaceBright = 292e23
$surfaceContainerLowest = 000000
$surfaceContainerLow = 11140e
$surfaceContainer = 171b13
$surfaceContainerHigh = 1d2118
$surfaceContainerHighest = 23271d
$onSurface = e3e7d8
$surfaceVariant = 23271d
$onSurfaceVariant = a8ad9f
$outline = 72776a
$outlineVariant = 454a3e
$inverseSurface = fafaf1
$inverseOnSurface = 54564f
$shadow = 000000
$scrim = 000000
$surfaceTint = b7ce9d
$primary = b7ce9d
$primaryDim = a9c090
$onPrimary = 334621
$primaryContainer = 445832
$onPrimaryContainer = d3ebb8
$inversePrimary = 51653d
$primaryFixed = d2eab8
$primaryFixedDim = c4dcaa
$onPrimaryFixed = 324520
$onPrimaryFixedVariant = 4d623a
$secondary = becbae
$secondaryDim = b1bda1
$onSecondary = 39442e
$secondaryContainer = 343f29
$onSecondaryContainer = b7c4a7
$secondaryFixed = dae7c9
$secondaryFixedDim = ccd9bb
$onSecondaryFixed = 38432d
$onSecondaryFixedVariant = 545f48
$tertiary = fff9ea
$tertiaryDim = f0e49e
$onTertiary = 686028
$tertiaryContainer = f9eca6
$onTertiaryContainer = 605720
$tertiaryFixed = f9eca6
$tertiaryFixedDim = ebde99
$onTertiaryFixed = 4d450f
$onTertiaryFixedVariant = 6a612a
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 697e53
$secondaryPaletteKeyColor = 6f7b62
$tertiaryPaletteKeyColor = 81783e
$neutralPaletteKeyColor = 767871
$neutralVariantPaletteKeyColor = 74796c
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 697e53
$secondary_paletteKeyColor = 6f7b62
$tertiary_paletteKeyColor = 81783e
$neutral_paletteKeyColor = 767871
$neutral_variant_paletteKeyColor = 74796c
$term0 = 343433
$term1 = 949600
$term2 = b1d96e
$term3 = d7f17c
$term4 = 8cb588
$term5 = c6a844
$term6 = add590
$term7 = d8dac4
$term8 = a3a493
$term9 = acaf00
$term10 = bced6f
$term11 = e5ff97
$term12 = b2c7a7
$term13 = cec06b
$term14 = bee899
$term15 = ffffff
$rosewater = f5f2e2
$flamingo = e6e3c3
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = ccd38b
$yellow = ebf6c8
$green = c0ed9e
$teal = beecb1
$sky = b0e9b0
$sapphire = 92d79e
$blue = 75cf9d
$lavender = 89dcc6
$klink = 419761
$klinkSelection = 3f9762
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 8e8c00
$knegativeSelection = 8c8d00
$kneutral = a4b400
$kneutralSelection = a3b400
$kpositive = 73bb4d
$kpositiveSelection = 71bb4e
$text = e3e7d8
$subtext1 = a8ad9f
$subtext0 = 72776a
$overlay2 = 64685c
$overlay1 = 55594e
$overlay0 = 474a41
$surface2 = 393c34
$surface1 = 2b2e27
$surface0 = 1c1e18
$base = 0d0f0a
$mantle = 0d0f0a
$crust = 0c0e09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
