wireplumber.settings = {
  # No forzar a que las aplicaciones se queden ancladas a una tarjeta previa
  linking.allow-fallback-linking = true
}

linking.rules = [
  {
    matches = [
      {
        node.name = "~.*"
      }
    ]
    actions = {
      update-props = {
        # Fuerza a los streams a seguir al sink predeterminado actual
        node.autoconnect = true
        node.dont-reconnect = false
      }
    }
  }
]
